# This is a basic workflow to help you get started with Actions

name: release

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 20 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # generate files 
      - name: clone dnsmasq-china-list
        # You may pin to the exact commit or the version.
        # uses: sudosubin/git-clone-action@8a93ce24d47782e30077508cccacf8a05a891bae
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          # Repository owner and name. Ex: sudosubin/git-clone-action
          repository: felixonmars/dnsmasq-china-list
          path: dnsmasq-china-list
      
      - name: generate china domain list
        run: cd dnsmasq-china-list && make SERVER=domestic SMARTDNS_SPEEDTEST_MODE=tcp:80 smartdns-domain-rules
      
      - name: copy conf files to master
        run: cp dnsmasq-china-list/accelerated-domains.china.domain.smartdns.conf release/china.conf && cp dnsmasq-china-list/apple.china.domain.smartdns.conf release/apple.conf
      
      - name: delete dep repo
        run: rm -r dnsmasq-china-list
      
      - name: append nexitally domains
        run: sh script/converter.sh '${{secrets.NEXITALLY}}' release/nexitally.conf
      
      - name: append flower domains
        run: sh script/converter.sh '${{secrets.FLOWER}}' release/flower.conf
      
      # docker build and release
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,darwin/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPONAME }}:latest

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/*
          tag: release
          overwrite: true
          file_glob: true
